name = "RL78"
slug = "arch-rl78"
repo_user = "CUB3D"
repo_repo = "ghidra-rl78"
kind = "DownloadOnly"

description = "Renesas RL78-S3 for Ghidra"
author = "CUB3D"
license = "Apache-2.0"
category = "processor"
homepage = ""
asset_pattern = "ghidra_*_PUBLIC_*_RL78.zip"
tags = ["ghidra-extension", "renesas-rl78"]
