name = "RX"
slug = "arch-renesasrx"
repo_user = "redballoonsecurity"
repo_repo = "rx-proc-ghidra"
kind = "ProcessorGit"
branch_name = "master"
no_prefix = true

description = "Renesas RX processor module for Ghidra"
author = "redballoonsecurity"
license = ""
category = "processor"
homepage = ""
asset_pattern = ""
tags = []
