name = "MCORE"
slug = "arch-mcore"
repo_user = "CUB3D"
repo_repo = "ghidra-mcore"
kind = "DownloadOnly"

description = "M-CORE architecture support in Ghidra"
author = "CUB3D"
license = "Apache-2.0"
category = "processor"
homepage = ""
asset_pattern = "ghidra_*_PUBLIC_*_MCORE.zip"
tags = ["ghidra-extension", "m-core"]
