name = "Binexport"
slug = "exporter-binexport"
repo_user = "google"
repo_repo = "binexport"
kind = "DownloadOnly"

description = "Export disassemblies into Protocol Buffers for use with BinDiff and BinNavi"
author = "google"
license = "Apache-2.0"
category = "exporter"
homepage = ""
asset_pattern = "BinExport_Ghidra-Java.zip"
tags = ["bindiff", "binexport", "binnavi", "ghidra", "ghidra-extension", "ghidra-plugin", "protobuf", "reverse-engineering"]
