name = "M16c"
slug = "arch-m16c"
repo_user = "silverchris"
repo_repo = "m16c"
kind = "ProcessorGit"
branch_name = "master"
no_prefix = true

description = "Ghidra processor module for the Renesas M16C architecture"
author = "silverchris"
license = ""
category = "processor"
homepage = ""
asset_pattern = ""
tags = []
