name = "XEXLoaderWV"
slug = "local-xexloaderwv"
repo_user = ""
repo_repo = ""
kind = "Local"
description = "Locally discovered extension: XEXLoaderWV"
author = ""
license = ""
category = "tool"
homepage = ""
asset_pattern = ""
tags = [
    "local",
]
local_path = "F:\\Software\\Dev\\Ghidra\\Ghidra_Extensions\\ghidra_11.3.2_PUBLIC_20250504_XEXLoaderWV.zip"
version = "11.3.2"
