name = "GhidraMCP"
slug = "local-ghidramcp"
repo_user = ""
repo_repo = ""
kind = "Local"
description = "Locally discovered extension: GhidraMCP"
author = ""
license = ""
category = "tool"
homepage = ""
asset_pattern = ""
tags = [
    "local",
]
local_path = "F:\\Software\\Dev\\Ghidra\\Ghidra_Extensions\\GhidraMCP-5.5.0.zip"
version = "12.0.4"
min_ghidra_version = "2025-03-22"
