name = "XboxExecutableLoader"
slug = "local-xboxexecutableloader"
repo_user = ""
repo_repo = ""
kind = "Local"
description = "Locally discovered extension: XboxExecutableLoader"
author = ""
license = ""
category = "tool"
homepage = ""
asset_pattern = ""
tags = [
    "local",
]
local_path = "F:\\Software\\Dev\\Ghidra\\Ghidra_Extensions\\ghidra_11.3.1_PUBLIC_20250411_ghidra-xbe.zip"
version = "11.3.1"
min_ghidra_version = "01/11/2020"
